<?php
/**
 * Database credentials API — works even when DB is offline.
 * Saves to config/db.local.php (never committed / not overwritten by deploy).
 */
error_reporting(E_ALL);
ini_set('display_errors', '0');
header('Content-Type: application/json; charset=utf-8');

set_exception_handler(function ($e) {
    http_response_code(500);
    echo json_encode(['ok' => false, 'error' => 'Server error: ' . $e->getMessage()]);
    exit;
});

set_error_handler(function ($severity, $message, $file, $line) {
    throw new ErrorException($message, 0, $severity, $file, $line);
});

function dbcfg_json($data, $status = 200) {
    http_response_code($status);
    echo json_encode($data);
    exit;
}

function dbcfg_body() {
    $raw = file_get_contents('php://input');
    if ($raw === false || $raw === '') {
        // Also accept classic form posts (some hosts/WAFs block raw JSON)
        if (!empty($_POST)) {
            return $_POST;
        }
        return [];
    }
    $data = json_decode($raw, true);
    return is_array($data) ? $data : [];
}

function dbcfg_local_path() {
    return dirname(__DIR__) . '/config/db.local.php';
}

function dbcfg_defaults() {
    return [
        'host' => 'localhost',
        'db' => 'timetracking',
        'user' => 'root',
        'pass' => '',
    ];
}

function dbcfg_read_local() {
    $path = dbcfg_local_path();
    $cfg = dbcfg_defaults();
    if (!is_readable($path)) {
        return [$cfg, false];
    }
    $host = $cfg['host'];
    $db = $cfg['db'];
    $user = $cfg['user'];
    $pass = $cfg['pass'];
    require $path;
    return [[
        'host' => (string) $host,
        'db' => (string) $db,
        'user' => (string) $user,
        'pass' => (string) $pass,
    ], true];
}

function dbcfg_write_local(array $cfg) {
    $path = dbcfg_local_path();
    $dir = dirname($path);
    if (!is_dir($dir) && !@mkdir($dir, 0755, true) && !is_dir($dir)) {
        return 'Could not create config directory — check folder permissions on the server';
    }
    if (!is_writable($dir)) {
        return 'config/ folder is not writable by PHP — chmod 755 the config folder';
    }
    $content = "<?php\n"
        . '// Generated by Time Tracking UI — do not commit.' . "\n"
        . '$host = ' . var_export($cfg['host'], true) . ";\n"
        . '$db   = ' . var_export($cfg['db'], true) . ";\n"
        . '$user = ' . var_export($cfg['user'], true) . ";\n"
        . '$pass = ' . var_export($cfg['pass'], true) . ";\n";

    if (@file_put_contents($path, $content, LOCK_EX) === false) {
        return 'Could not write config/db.local.php — check folder permissions';
    }
    @chmod($path, 0644);
    return null;
}

function dbcfg_try_connect(array $cfg) {
    if (!class_exists('mysqli')) {
        return [null, 'PHP mysqli extension is not enabled on this host'];
    }
    mysqli_report(MYSQLI_REPORT_OFF);
    $conn = @new mysqli($cfg['host'], $cfg['user'], $cfg['pass'], $cfg['db']);
    if ($conn->connect_error) {
        return [null, $conn->connect_error];
    }
    $conn->set_charset('utf8mb4');
    return [$conn, null];
}

function dbcfg_install_schema(mysqli $conn) {
    $sqlFile = dirname(__DIR__) . '/sql/schema.sql';
    if (!is_readable($sqlFile)) {
        return 'sql/schema.sql not found on server';
    }
    $sql = file_get_contents($sqlFile);
    // When DB already selected, strip CREATE DATABASE / USE lines
    $sql = preg_replace('/^\s*CREATE\s+DATABASE\b.*?;\s*/im', '', $sql);
    $sql = preg_replace('/^\s*USE\s+\S+\s*;\s*/im', '', $sql);

    if ($conn->multi_query($sql)) {
        do {
            if ($result = $conn->store_result()) {
                $result->free();
            }
        } while ($conn->more_results() && $conn->next_result());
    }
    if ($conn->errno) {
        return $conn->error;
    }
    return null;
}

$method = $_SERVER['REQUEST_METHOD'];

if ($method === 'GET') {
    list($cfg, $hasLocal) = dbcfg_read_local();
    list($conn, $err) = dbcfg_try_connect($cfg);
    $tablesOk = false;
    if ($conn) {
        $res = $conn->query("SHOW TABLES LIKE 'time_entries'");
        $tablesOk = $res && $res->num_rows > 0;
        $conn->close();
    }
    dbcfg_json([
        'ok' => true,
        'connected' => $err === null,
        'error' => $err,
        'has_local_file' => $hasLocal,
        'tables_ready' => $tablesOk,
        'config' => [
            'host' => $cfg['host'],
            'db' => $cfg['db'],
            'user' => $cfg['user'],
            'has_password' => $cfg['pass'] !== '',
        ],
    ]);
}

if ($method === 'POST' || $method === 'PUT') {
    $body = dbcfg_body();
    list($existing, $hasLocal) = dbcfg_read_local();

    $host = trim((string) ($body['host'] ?? $existing['host']));
    $db = trim((string) ($body['db'] ?? $existing['db']));
    $user = trim((string) ($body['user'] ?? $existing['user']));
    $pass = array_key_exists('pass', $body) ? (string) $body['pass'] : null;
    $keepPass = !empty($body['keep_password']);
    $installSchema = !empty($body['install_schema']);
    $testOnly = !empty($body['test_only']);

    if ($host === '' || $db === '' || $user === '') {
        dbcfg_json(['ok' => false, 'error' => 'Host, database name, and username are required'], 400);
    }

    if ($pass === null || ($keepPass && $pass === '')) {
        $pass = $existing['pass'];
    }

    $cfg = [
        'host' => $host,
        'db' => $db,
        'user' => $user,
        'pass' => $pass,
    ];

    list($conn, $err) = dbcfg_try_connect($cfg);
    if ($err !== null) {
        dbcfg_json([
            'ok' => false,
            'error' => 'Connection failed: ' . $err,
            'connected' => false,
        ], 400);
    }

    if ($testOnly) {
        $conn->close();
        dbcfg_json(['ok' => true, 'connected' => true, 'message' => 'Connection successful']);
    }

    $writeErr = dbcfg_write_local($cfg);
    if ($writeErr !== null) {
        $conn->close();
        dbcfg_json(['ok' => false, 'error' => $writeErr], 500);
    }

    $schemaMsg = null;
    if ($installSchema) {
        $schemaErr = dbcfg_install_schema($conn);
        if ($schemaErr !== null) {
            $conn->close();
            dbcfg_json([
                'ok' => false,
                'error' => 'Credentials saved, but schema install failed: ' . $schemaErr,
                'saved' => true,
            ], 500);
        }
        $schemaMsg = 'Tables installed/updated';
    }

    $res = $conn->query("SHOW TABLES LIKE 'time_entries'");
    $tablesOk = $res && $res->num_rows > 0;
    $conn->close();

    dbcfg_json([
        'ok' => true,
        'saved' => true,
        'connected' => true,
        'tables_ready' => $tablesOk,
        'message' => $schemaMsg ?: 'Database credentials saved',
        'config' => [
            'host' => $cfg['host'],
            'db' => $cfg['db'],
            'user' => $cfg['user'],
            'has_password' => $cfg['pass'] !== '',
        ],
    ]);
}

dbcfg_json(['ok' => false, 'error' => 'Method not allowed'], 405);
